---
title: 'Final Project: Guidance Document'
author: "Sawan Pandita"
date: "Due Sunday of Week 14"
output:  html_notebook
---

# Purpose

*This document is required to indicate where various requirements can be found within your Final Project Report Rmd.  You must* **indicate line numbers as they appear in your final Rmd document** *accompanying each of the following required tasks. Points will be deducted if line numbers are missing or differ signficantly from the submitted Final Rmd document.*  


# Final Project Requirements


### Data Access

*Description: (1) Analysis includes at least two different data sources. (2) Primary data source may NOT be loaded from an R package--though supporting data may. (3) Access to all data sources is contained within the analysis. (4) Imported data is inspected at beginning of analysis using one or more R functions: e.g., str, glimpse, head, tail, names, nrow, etc*

(A) .Rmd Line numbers where at least two different data sources are imported:  
Lines 84, 85,86

(B) .Rmd Line numbers for inspecting data intake:  
Lines 88 to 90

### Data Wrangling (5 out of 8 required)

*Description: Students need not use every function and method introduced in STAT 184, but clear demonstration of proficiency should include proper use of 5 out of the following 8 topics from class: (+) various data verbs for general data wrangling like filter, mutate, summarise, arrange, group_by, etc. (+) joins for multiple data tables. (+) spread & gather to stack/unstack variables (+) regular expressions (+) reduction and/or transformation functions like mean, sum, max, min, n(), rank, pmin, etc. (+) user-defined functions (+) loops and control flow (+) machine learning*


(A) .Rmd Line number(s) for general data wrangling: 

filter(): Lines 116, 119, 261, 377, 504, 655, 672, 684, 859, 864
group_by(): Lines 101, 203, 232, 253, 363, 495, 656, 673, 687, 818, 824,836, 848 
summarise(): 102, 106, 204, 233, 254, 364, 412, 496, 657, 674, 819, 825, 837, 849
mutate(): 505, 547, 654, 663, 680, 689, 855, 
arrange(): 295, 545, 688,  
select(): 297, 358

(B) .Rmd Line number(s) for a join operation: 
Lines 228, 356: inner_join()
Line 863: left_join()
Line 661, 841: full_join()

(C) .Rmd Line number(s) for a spread or gather operation (or equivalent):

Lines 237: pivot_wider() operation for runs data
Lines 245, 667, 843: pivot_longer() operation to reshape data,pivot_longer() for team data

(D) .Rmd Line number(s) for use of regular expressions: 


(E) .Rmd Line number(s) for use of reduction and/or transformation functions: 

Line 111, 234, 255, 365, 371, 820, 826,827 : sum()
Line 107, 413-414, : mean()
Lines 899 : median()
Lines 102, 110, 204, 256, 366, 497, 658, 821, 838 : n(), 
Lines 258, 368, 498, 675, 828, 850, : n_distinct()

(F) .Rmd Line number(s) for use of user-defined functions: 

Lines 640, 654, 664 - 665: standardize_team_names()
Lines 652, 751 : prepare_team_data()
Lines 698, 752 : create_team_performance_plot()

(G) .Rmd Line number(s) for use of loops and/or control flow: 


(H) .Rmd Line number(s) for use of machine learning (not "wrangling" but scored here): 

Line 267, 392, 421, 516, 710, 888: geom_smooth(method = "loess") uses LOESS regression
Line 568: lm() for linear regression modeling


### Data Visualization (3 of 5 required)

*Description: Students need not use every function and method introduced in STAT 184, but clear demonstration of proficiency should include a range of useful of data visualizations that are (1) relevant to stated research question for the analysis, (2) include at least one effective display of many--at least 3--variables, and (3) include 3 of the following 5 visualization techniques learned in STAT 184: (+) use of multiple geoms such as points, density, lines, segments, boxplots, bar charts, histograms, etc (+) use of multiple aesthetics--not necessarily all in the same graph--such as color, size, shape, x/y position, facets, etc (+) layered graphics such as points and accompanying smoother, points and accompanying boxplots, overlaid density distributions, etc (+) leaflet maps (+) decision tree and/or dendogram displaying machine learning model results*


(A) .Rmd Line number(s) for use of mulitple different geoms:  

Line 124, 208 : geom_bar()
Line 130, 134, 266, 388, 419, 515, 714, 883 : geom_point()
Line 267, 392, 421, 516, 710, 888 : geom_smooth()
Line 533, : geom_density()
Line 130, 134, 266, 388, 419, 515, 714, 883 : geom_line() and geom_point()

(B) .Rmd Line number(s) for use of multiple aesthetics:  

Lines 122, 
Lines 130, 135, 207, 265, 387 - 389, 419, 421, 514 - 515, 532 -533, 552 -553, 701, 710, 878, 884 : aes using color, group, alpha, size
Lines 703: faceting with facet_wrap()


(C) .Rmd Line number(s) for use of layered graphics:  

Line 130, 134, 266, 388, 419, 515, 714, 883 : geom_point()
Line 267, 392, 421, 516, 710, 888 : geom_smooth()
Line 533 : geom_density()
Line 532 : geom_histogram()
Player Impact Plot (most effective example): Lines : 875 - 893

(D) .Rmd Line number(s) for use of leaflet maps:  

(E) .Rmd Line number(s) for use of decision tree or dendogram results:    




### Other requirements (Nothing for you to report in this Guidance Document)

(A) *All data visualizations* must be relevant to the stated research question, and the report must include at least one effective display of many--at least 3--variables 

(B) *Code quality:* Code formatting is consistent with Style Guide Appendix of DataComputing eBook. Specifically, all code chunks demonstrate proficiency with (1) meaningful object names (2) proper use of white space especially with respect to infix operators, chain operators, commas, brackets/parens, etc (3) use of `<-` assignment operator throughout (4) use of meaningful comments.

(C) *Narrative quality:* The narrative text (1) clearly states one research question that motivates the overall analysis, (2) explains reasoning for each significant step in the analysis and it's relationship to the research question, (3) explains significant findings and conclusions as they relate to the research question, and (4) is completely free of errors in spelling and grammar

(D) *Overall Quality:* Submitted project shows significant effort to produce a high-quality and thoughtful analysis that showcases STAT 184 skills. (2) The project must be self-contained, such that the analysis can be entirely rerun without errors. (3) Analysis is coherent, well-organized, and free of extraneous content such as data dumps, unrelated graphs, and other content that is not overtly connected to the research question.




